### ISSUE TITLE
More details for the usage of this tool?

### ISSUE THREAD

**Issue by sjytker** [kanezaki/selective_search_3d#1]
**I have install ROS Kinect on Ubuntu16.04.
I haven't used ROS toolkit before and it seems your code is heavily based on it.
Is there any rules I missed?
When I try your first command 'roslaunch freenect_launch freenect.launch', it fails with the following error:**

[freenect.launch] is neither a launch file in package [freenect_launch] nor is [freenect_launch] a launch file name
The traceback for the exception was written to the log file

**Comment by kanezaki** [comment]
If you use Kinect with ROS, please install _freenect_launch_ repository.
`$ sudo apt install ros-kinetic-freenect-launch`

More information aboutn _freenect_launch_ can be found here.
http://wiki.ros.org/freenect_launch
